<#
.SYNOPSIS
    Búsqueda del glosario de términos de ITIL4 en línea de comandos.
.DESCRIPTION
    Búsqueda de texto en las definiciones del glosario de términos de ITIL4 en línea de comandos. Sacado del PDF de glosario de términos de ITIL V4
.EXAMPLE
    itil instrucción
    Busca las definiciones de los términos o términos que incluyan la palabra "instrucción"
.EXAMPLE
    itil process -English
    Busca las definiciones de los términos o términos que incluyan la palabra en inglés "process"
.EXAMPLE
    Get-IITLTermDefinicion engage -English
    Busca las definiciones de los términos o términos que incluyan la palabra en inglés "engage"
.EXAMPLE
    Get-IITLTermDefinicion incidente
    Busca las definiciones de los términos o términos que incluyan la palabra "inclidente"
#>
function Get-ITILTermDefinition {
    param(
        #TEXTO DE BUSQUEDA POR PALABAS SIN ESPECIFICAR COMILLAS
        [Parameter(ValueFromRemainingArguments,Mandatory=$true)]
        [string]$busqueda,
        #OPCION DE BÚSQUEDA DE TEXTO EN INGLÉS
        [Parameter(Mandatory=$false)]
        [switch]$English
    )
    #LISTADO DE TERMINOS EN UN OBJETO
    $Glosario=@(
    [pscustomobject]@{term='acceptance criteria';termino='criterios de aceptación';english='A list of minimum requirements that a service or service component must meet for it to be acceptable to key stakeholders.';spanish='Una lista de requerimientos mínimos con los que un servicio o componente de un servicio debe cumplir para que las partes interesadas clave lo consideren aceptable.'}
    [pscustomobject]@{term='Agile';termino='Agile';english='An umbrella term for a collection of frameworks and techniques that together enable teams and individuals to work in a way that is typified by collaboration, prioritization, iterative and incremental delivery, and timeboxing. There are several specific methods (or frameworks) that are classed as Agile, such as Scrum, Lean, and Kanban.';spanish='Término que engloba una serie de marcos de referencia y técnicas que, en su conjunto, habilitan equipos e individuos para trabajar de una forma que se caracteriza por la colaboración, la priorización, la entrega iterativa y gradual, y tiempos previamente acordados para su cumplimiento. Hay varios métodos específicos (o marcos de referencia) que se clasifican como Agile, por ejemplo, Scrum, Lean y Kanban.'}
    [pscustomobject]@{term='architecture management practice';termino='práctica de gestión de la arquitectura';english='The practice of providing an understanding of all the different elements that make up an organization and how those elements relate to one another.';spanish='Práctica que permite comprender los distintos elementos que conforman una organización y cómo se relacionan entre sí.'}
    [pscustomobject]@{term='asset register';termino='registro de activos';english='A database or list of assets, capturing key attributes such as ownership and financial value.';spanish='Base de datos o lista de activos que incluye sus atributos clave, como propiedad y valor financiero.'}
    [pscustomobject]@{term='availability';termino='disponibilidad';english='The ability of an IT service or other configuration item to perform its agreed function when required.';spanish='La habilidad de un servicio de TI u otro elemento de configuración para realizar su función acordada cuando sea requerido.'}
    [pscustomobject]@{term='availability management practice';termino='práctica de gestión de la disponibilidad';english='The practice of ensuring that services deliver agreed levels of availability to meet the needs of customers and users.';spanish='Práctica que consiste en asegurar que los servicios entregan los niveles acordados de disponibilidad para satisfacer las necesidades de clientes y usuarios.'}
    [pscustomobject]@{term='baseline';termino='línea base';english='A report or metric that serves as a starting point against which progress or change can be assessed.';spanish='Informe o métrica que sirve como punto de partida para evaluar los progresos o cambios.'}
    [pscustomobject]@{term='best practice';termino='mejores prácticas';english='A way of working that has been proven to be successful by multiple organizations.';spanish='Forma de trabajar cuya eficacia ha sido comprobada por múltiples organizaciones.'}
    [pscustomobject]@{term='big data';termino='big data';english='The use of very large volumes of structured and unstructured data from a variety of sources to gain new insights.';spanish='El uso de volúmenes muy grandes de datos estructurados y no estructurados provenientes de diferentes fuentes que permiten obtener nuevo conocimiento.'}
    [pscustomobject]@{term='business analysis practice';termino='práctica de análisis empresarial';english='The practice of analysing a business or some element of a business, defining its needs and recommending solutions to address these needs and/or solve a business problem, and create value for stakeholders.';spanish='Práctica que consiste en analizar un negocio o algún elemento de este, definir sus necesidades y recomendar soluciones para satisfacer dichas necesidades o para abordar algún problema empresarial y crear valor para las partes interesadas.'}
    [pscustomobject]@{term='business case';termino='caso de negocio';english='A justification for expenditure of organizational resources, providing information about costs, benefits, options, risks, and issues.';spanish='Una justificación del gasto de recursos organizacionales que incluye información sobre costos, beneficios, opciones, riesgos y problemáticas.'}
    [pscustomobject]@{term='business impact analysis (BIA)';termino='análisis de impacto al negocio (BIA)';english='A key activity in the practice of service continuity management that identifies vital business functions and their dependencies.';spanish='Actividad clave en la práctica de gestión de la continuidad del servicio que identifica las funciones vitales del negocio y sus dependencias.'}
    [pscustomobject]@{term='business relationship manager (BRM)';termino='gerente de relaciones con el negocio (BRM)';english='A role responsible for maintaining good relationships with one or more customers.';spanish='Un rol responsable de mantener buenas relaciones con uno o más clientes.'}
    [pscustomobject]@{term='call';termino='llamada';english='An interaction (e.g. a telephone call) with the service desk. A call could result in an incident or a service request being logged.';spanish='Interacción (por ejemplo, una llamada telefónica) con la mesa de servicio. Una llamada podría resultar en el registro de un incidente o una solicitud de servicio.'}
    [pscustomobject]@{term='call/contact centre';termino='centro de atención telefónica o de contacto';english='An organization or business unit that handles large numbers of incoming and outgoing calls and other interactions.';spanish='Unidad del negocio o la organización que atiende una gran cantidad de llamadas entrantes y salientes, así como otras interacciones.'}
    [pscustomobject]@{term='capability';termino='competencia';english='The ability of an organization, person, process, application, configuration item, or IT service to carry out an activity.';spanish='La capacidad de una organización, una persona, un proceso, una aplicación, un elemento de configuración o un servicio de TI para llevar a cabo una actividad.'}
    [pscustomobject]@{term='capacity and performance management practice';termino='práctica de gestión de la capacidad y el desempeño';english='The practice of ensuring that services achieve agreed and expected performance levels, satisfying current and future demand in a cost-effective way.';spanish='Práctica que consiste en asegurar que los servicios logren los niveles de desempeño esperados y acordados, para satisfacer la demanda actual y futura de forma rentable.'}
    [pscustomobject]@{term='capacity planning';termino='planificación de la capacidad';english='The activity of creating a plan that manages resources to meet demand for services.';spanish='Actividad que consiste en la creación de un plan con el que se gestionen los recursos para satisfacer la demanda de servicios.'}
    [pscustomobject]@{term='change';termino='cambio';english='The addition, modification, or removal of anything that could have a direct or indirect effect on services.';spanish='Adición, modificación o eliminación de algún elemento que pueda tener un efecto directo o indirecto en los servicios.'}
    [pscustomobject]@{term='change authority';termino='autoridad de cambios';english='A person or group responsible for authorizing a change.';spanish='Persona o grupo responsable de autorizar un cambio.'}
    [pscustomobject]@{term='change control practice';termino='práctica de control de cambios';english='The practice of ensuring that risks are properly assessed, authorizing changes to proceed and managing a change schedule in order to maximize the number of successful service and product changes.';spanish='Práctica que consiste en asegurar la evaluación adecuada de los riesgos, autorizar la aplicación de cambios y gestionar un calendario de cambios para maximizar el número de cambios satisfactorios de productos y servicios.'}
    [pscustomobject]@{term='change model';termino='modelo de cambios';english='A repeatable approach to the management of a particular type of change.';spanish='Enfoque repetible para la gestion de un tipo particular de cambio.'}
    [pscustomobject]@{term='change schedule';termino='calendario de cambios';english='A calendar that shows planned and historical changes.';spanish='Calendario que muestra el historial de cambios y los cambios planificados.'}
    [pscustomobject]@{term='charging';termino='cobro';english='The activity that assigns a price for services.';spanish='Actividad que asigna un precio a un servicio.'}
    [pscustomobject]@{term='cloud computing';termino='cómputo en la nube';english='A model for enabling on-demand network access to a shared pool of configurable computing resources that can be rapidly provided with minimal management effort or provider interaction.';spanish='Modelo para habilitar el acceso de red bajo demanda a un grupo compartido de recursos informáticos configurables que se pueden proporcionar rápidamente con un mínimo esfuerzo de gestion o interacción por parte del proveedor.'}
    [pscustomobject]@{term='compliance';termino='conformidad';english='The act of ensuring that a standard or set of guidelines is followed, or that proper, consistent accounting or other practices are being employed.';spanish='El acto que consiste en asegurar que se sigue una norma o un conjunto de directrices, o que se aplican prácticas de contabilidad o de otro tipo de forma adecuada y consistente.'}
    [pscustomobject]@{term='confidentiality';termino='confidencialidad';english='A security objective that ensures information is not made available or disclosed to unauthorized entities.';spanish='Objetivo de seguridad para asegurar que la información no se comunique o revele a entidades no autorizadas.'}
    [pscustomobject]@{term='configuration';termino='configuración';english='An arrangement of configuration items (CIs) or other resources that work together to deliver a product or service. Can also be used to describe the parameter settings for one or more CIs.';spanish='Disposición de elementos de configuración (CI) u otros recursos que funcionan conjuntamente para ofrecer un producto o servicio. También se puede usar para describir el establecimiento de parámetros de uno o más CIs.'}
    [pscustomobject]@{term='configuration item (CI)';termino='elemento de configuración (CI)';english='Any component that needs to be managed in order to deliver an IT service.';spanish='Cualquier componente que se requiera gestionar para poder entregar un servicio de TI.'}
    [pscustomobject]@{term='configuration management database (CMDB)';termino='base de datos de gestión de la configuración (CMDB)';english='A database used to store configuration records throughout their lifecycle. The CMDB also maintains the relationships between configuration records.';spanish='Base de datos utilizada para almacenar los registros de configuración a lo largo de su ciclo de vida. En la CMDB también se conservan las relaciones entre los registros de configuración.'}
    [pscustomobject]@{term='configuration management system (CMS)';termino='sistema de gestión de la configuración (CMS)';english='A set of tools, data, and information that is used to support service configuration management.';spanish='Conjunto de herramientas, datos e información que se utiliza para respaldar la gestión de la configuración del servicio.'}
    [pscustomobject]@{term='configuration record';termino='registro de configuración';english='A record containing the details of a configuration item (CI). Each configuration record documents the lifecycle of a single CI. Configuration records are stored in a configuration management database.';spanish='Registro que contiene los detalles de un elemento de configuración (CI). Cada registro de configuración documenta el ciclo de vida de un solo CI. Los registros de configuración se almacenan en una base de datos de gestión de la configuración.'}
    [pscustomobject]@{term='continual improvement practice';termino='práctica de mejora continua';english='The practice of aligning an organization"s practices and services with changing business needs through the ongoing identification and improvement of all elements involved in the effective management of products and services.';spanish='Práctica que consiste en alinear las prácticas y los servicios de una organización con las necesidades cambiantes del negocio a través de la identificación y mejora continuas de todos los elementos involucrados en la gestión eficaz de productos y servicios.'}
    [pscustomobject]@{term='continuous deployment';termino='implementación continua';english='An integrated set of practices and tools used to deploy software changes into the production environment. These software changes have already passed pre-defined automated tests.';spanish='Conjunto integrado de prácticas y herramientas usado para implementar los cambios de software en el ambiente de producción. Dichos cambios de software habrán superado previamente pruebas automatizadas predefinidas.'}
    [pscustomobject]@{term='continuous integration / continuous delivery';termino='integración continua/entrega continua';english='An integrated set of practices and tools used to merge developers" code, build and test the resulting software, and package it so that it is ready for deployment.';spanish='Conjunto integrado de prácticas y herramientas usado para fusionar el código de los desarrolladores, crear y probar el software resultante y empaquetarlo de modo que esté listo para la implementación.'}
    [pscustomobject]@{term='control';termino='control';english='The means of managing a risk, ensuring that a business objective is achieved, or that a process is followed.';spanish='Medio para gestionar un riesgo, asegurando la consecución de un objetivo empresarial o el seguimiento de un proceso.'}
    [pscustomobject]@{term='cost';termino='costo';english='The amount of money spent on a specific activity or resource.';spanish='Cantidad de dinero que se gasta en una actividad o un recurso específicos.'}
    [pscustomobject]@{term='cost centre';termino='centro de costos';english='A business unit or project to which costs are assigned.';spanish='Unidad del negocio o proyecto al que se asignan los costos.'}
    [pscustomobject]@{term='critical success factor (CSF)';termino='factor crítico de éxito (CSF)';english='A necessary precondition for the achievement of intended results.';spanish='Precondición necesaria para lograr los resultados deseados.'}
    [pscustomobject]@{term='culture';termino='cultura';english='A set of values that is shared by a group of people, including expectations about how people should behave, ideas, beliefs, and practices.';spanish='Conjunto de valores que es compartido por un grupo de personas, que incluye expectativas de comportamiento, ideas, creencias y prácticas.'}
    [pscustomobject]@{term='customer';termino='cliente';english='A person who defines the requirements for a service and takes responsibility for the outcomes of service consumption.';spanish='Persona que define los requerimientos de un servicio y es responsable de las consecuencias de consumo del servicio.'}
    [pscustomobject]@{term='customer experience (CX)';termino='experiencia del cliente (CX)';english='The sum of functional and emotional interactions with a service and service provider as perceived by a service consumer.';spanish='Suma de las interacciones funcionales y emocionales con un servicio y un proveedor de servicios percibidas por el consumidor del servicio.'}
    [pscustomobject]@{term='dashboard';termino='cuadro de mando (dashboard, tablero de mando)';english='A real-time graphical representation of data.';spanish='Representación gráfica de los datos en tiempo real.'}
    [pscustomobject]@{term='deliver and support';termino='entrega y asistencia';english='The value chain activity that ensures services are delivered and supported according to agreed specifications and stakeholders" expectations.';spanish='Actividad de la cadena de valor para asegurar que los servicios son entregados y soportados de acuerdo con las especificaciones acordadas y las expectativas de las partes interesadas.'}
    [pscustomobject]@{term='demand';termino='demanda';english='Input to the service value system based on opportunities and needs from internal and external stakeholders.';spanish='Entrada al sistema de valores del servicio que se basa en las oportunidades y las necesidades de las partes interesadas internas y externas.'}
    [pscustomobject]@{term='deployment';termino='implementación';english='The movement of any service component into any environment.';spanish='Movimiento de cualquier componente del servicio a cualquier ambiente.'}
    [pscustomobject]@{term='deployment management practice';termino='práctica de gestión de la implementación';english='The practice of moving new or changed hardware, software, documentation, processes, or any other service component to live environments.';spanish='Práctica que consiste en mover hardware, software, documentación, procesos o cualquier otro componente de servicio nuevo o modificado a ambientes de producción.'}
    [pscustomobject]@{term='design and transition';termino='diseño y transición';english='The value chain activity that ensures products and services continually meet stakeholder expectations for quality, costs, and time to market.';spanish='Actividad de la cadena de valor que asegura que los productos y servicios cumplen de forma continua las expectativas de las partes interesadas sobre la calidad, los costos y el tiempo de salida al mercado.'}
    [pscustomobject]@{term='design thinking';termino='design thinking';english='A practical and human-centred approach used by product and service designers to solve complex problems and find practical and creative solutions that meet the needs of an organization and its customers.';spanish='Enfoque práctico y centrado en las personas utilizado por los diseñadores de productos y servicios para resolver problemas complejos y encontrar soluciones prácticas y creativas que satisfagan las necesidades de una organización y de sus clientes.'}
    [pscustomobject]@{term='development environment';termino=';ambiente de desarrollo';english='An environment used to create or modify IT services or applications.';spanish='Ambiente que se utiliza para crear o modificar servicios de TI o aplicaciones.'}
    [pscustomobject]@{term='DevOps';termino='DevOps';english='An organizational culture that aims to improve the flow of value to customers. DevOps focuses on culture, automation, Lean, measurement, and sharing (CALMS).';spanish='Cultura organizacional que tiene la finalidad de mejorar el flujo de valor para los clientes. DevOps se centra en la cultura, la automatización, el método Lean, la medición y el uso compartido (CALMS).'}
    [pscustomobject]@{term='digital transformation';termino='transformación digital';english='The evolution of traditional business models to meet the needs of highly empowered customers, with technology playing an enabling role.';spanish='La evolución de los modelos de negocio tradicionales orientada a cumplir con las necesidades de clientes que han adquirido mayor autonomía (influencia) y para los que la tecnología desempeña un papel fundamental.'}
    [pscustomobject]@{term='disaster';termino='desastre';english='A sudden unplanned event that causes great damage or serious loss to an organization. A disaster results in an organization failing to provide critical business functions for some predetermined minimum period of time.';spanish='Evento repentino y no planeado que provoca grandes daños o pérdidas importantes en una organización. Un desastre dentro de una organización que conlleva la incapacidad de proveer funciones críticas de negocio durante un tiempo mínimo predeterminado. '}
    [pscustomobject]@{term='disaster recovery plans';termino='planes de recuperación ante desastres';english='A set of clearly defined plans related to how an organization will recover from a disaster as well as return to a pre-disaster condition, considering the four dimensions of service management.';spanish='Conjunto de planes claramente definidos sobre la forma en que una organización se recuperará de un desastre y regresará al estado previo al desastre, y que tienen en cuenta las cuatro dimensiones de la gestión de servicios.'}
    [pscustomobject]@{term='driver';termino='driver';english='Something that influences strategy, objectives, or requirements.';spanish='Algo que influye en la estrategia, los objetivos o los requerimientos.'}
    [pscustomobject]@{term='effectiveness';termino='eficacia';english='A measure of whether the objectives of a practice, service or activity have been achieved.';spanish='Medida que sirve para ver si se han alcanzado los objetivos de una práctica, un servicio o una actividad.'}
    [pscustomobject]@{term='efficiency';termino='eficiencia';english='A measure of whether the right amount of resources have been used by a practice, service, or activity.';spanish='Medida que sirve para comprobar si una práctica, un servicio o una actividad han utilizado la cantidad adecuada de recursos.'}
    [pscustomobject]@{term='emergency change';termino='cambio de emergencia';english='A change that must be introduced as soon as possible.';spanish='Cambio que debe implementarse lo antes posible.'}
    [pscustomobject]@{term='engage';termino='comprometer';english='The value chain activity that provides a good understanding of stakeholder needs, transparency, continual engagement, and good relationships with all stakeholders.';spanish='Actividad de la cadena de valor que proporciona una comprensión adecuada de las necesidades de las partes interesadas, transparencia, participación continua y fomenta buenas relaciones con todas las partes interesadas.'}
    [pscustomobject]@{term='environment';termino='ambiente';english='A subset of the IT infrastructure that is used for a particular purpose, for example a live environment or test environment. Can also mean the external conditions that influence or affect something.';spanish='Subconjunto de la infraestructura de TI que se utiliza para un propósito en particular, como el ambiente de producción o el ambiente de prueba. También puede hacer referencia a las condiciones externas que influyen o afectan sobre algo.'}
    [pscustomobject]@{term='error';termino='error';english='A flaw or vulnerability that may cause incidents.';spanish='Defecto o vulnerabilidad que puede causar incidentes.'}
    [pscustomobject]@{term='error control';termino='control de errores';english='Problem management activities used to manage known errors.';spanish='Actividades de gestión de problemas que se usan para gestionar errores conocidos.'}
    [pscustomobject]@{term='escalation';termino='escalamiento';english='The act of sharing awareness or transferring ownership of an issue or work item.';spanish='Acto de informar o transferir la propiedad de una problemática a un elemento de trabajo.'}
    [pscustomobject]@{term='event';termino='Evento';english='Any change of state that has significance for the management of a service or other configuration item.';spanish='Cualquier cambio de estado que es significativo para la gestión de un servicio u otro elemento de configuración.'}
    [pscustomobject]@{term='external customer';termino='cliente externo';english='A customer who works for an organization other than the service provider.';spanish='Cliente que trabaja para una organización diferente a la del proveedor de servicios.'}
    [pscustomobject]@{term='failure';termino='falla';english='A loss of ability to operate to specification, or to deliver the required output or outcome.';spanish='Pérdida de la capacidad para operar de acuerdo con las especificaciones o para entregar la salida o la consecuencia requeridas.'}
    [pscustomobject]@{term='feedback loop';termino='bucle de retroalimentación';english='A technique whereby the outputs of one part of a system are used as inputs to the same part of the system.';spanish='Técnica en la que la información obtenida de una parte de un sistema se utiliza como dato de entrada para la misma parte del sistema.'}
    [pscustomobject]@{term='four dimensions of service management';termino='cuatro dimensiones de la gestión de servicios';english='The four perspectives that are critical to the effective and efficient facilitation of value for customers and other stakeholders in the form of products and services.';spanish='Las cuatro perspectivas que son críticas para proporcionar valor en forma de productos y servicios a clientes y otras partes interesadas de forma eficaz y efectiva.'}
    [pscustomobject]@{term='goods';termino='bienes';english='Tangible resources that are transferred or available for transfer from a service provider to a service consumer, together with ownership and associated rights and responsibilities.';spanish='Recursos tangibles que son transferidos o que están disponibles para transferirse de un proveedor de servicios a un consumidor de servicios, junto con la propiedad y los derechos y responsabilidades asociados.'}
    [pscustomobject]@{term='governance';termino='gobierno';english='The means by which an organization is directed and controlled.';spanish='Medios por los que se dirige y controla una organización.'}
    [pscustomobject]@{term='identity';termino='identidad';english='A unique name that is used to identify and grant system access rights to a user, person, or role.';spanish='Nombre único que se utiliza para identificar y conceder privilegios de acceso al sistema a un usuario, persona o rol.'}
    [pscustomobject]@{term='improve';termino='mejorar';english='The value chain activity that ensures continual improvement of products, services, and practices across all value chain activities and the four dimensions of service management.';spanish='Actividad de la cadena de valor que asegura una mejora continua de los productos, servicios y prácticas en todas las actividades de la cadena de valor y en las cuatro dimensiones de la gestión de servicios.'}
    [pscustomobject]@{term='incident';termino='incidente';english='An unplanned interruption to a service or reduction in the quality of a service.';spanish='Interrupción de un servicio o reducción en la calidad de un servicio no planificadas.'}
    [pscustomobject]@{term='incident management';termino='gestión de incidentes';english='The practice of minimizing the negative impact of incidents by restoring normal service operation as quickly as possible.';spanish='Práctica que consiste en minimizar el impacto negativo de incidentes mediante la restauración de la operación normal del servicio lo más rápidamente posible.'}
    [pscustomobject]@{term='information and technology';termino='información y tecnología';english='One of the four dimensions of service management. It includes the information and knowledge used to deliver services, and the information and technologies used to manage all aspects of the service value system.';spanish='Una de las cuatro dimensiones de la gestión de servicios. Incluye la información y el conocimiento utilizados para proporcionar servicios, y la información y las tecnologías usadas para gestionar todos los aspectos del sistema de valor del servicio.'}
    [pscustomobject]@{term='information security management practice';termino='práctica de gestión de la seguridad de la información';english='The practice of protecting an organization by understanding and managing risks to the confidentiality, integrity, and availability of information.';spanish='Práctica que consiste en proteger una organización mediante el conocimiento y la gestión de los riesgos de confidencialidad, integridad y disponibilidad de la información.'}
    [pscustomobject]@{term='information security policy';termino='política de seguridad de la información';english='The policy that governs an organization"s approach to information security management.';spanish='Política que gobierna el enfoque de una organización relativo a la gestión de la seguridad de la información.'}
    [pscustomobject]@{term='infrastructure and platform management practice';termino='práctica de gestión de plataformas einfraestructura';english='The practice of overseeing the infrastructure and platforms used by an organization. This enables the monitoring of technology solutions available, including solutions from third parties.';spanish='Práctica que consiste en supervisar la infraestructura y las plataformas que usa una organización. Permite monitorear las soluciones tecnológicas disponibles, incluidas las soluciones de terceros.'}
    [pscustomobject]@{term='integrity';termino='integridad';english='A security objective that ensures information is only modified by authorized personnel and activities.';spanish='Objetivo de seguridad que asegura que solo las actividades y el personal autorizados puedan modificar la información.'}
    [pscustomobject]@{term='internal customer';termino='cliente interno';english='A customer who works for the same organization as the service provider.';spanish='Cliente que trabaja para la misma organización que el proveedor de servicios.'}
    [pscustomobject]@{term='Internet of Things';termino='Internet de las Cosas (IoT) ';english='The interconnection of devices via the internet that were not traditionally thought of as IT assets, but now include embedded computing capability and network connectivity.';spanish='Interconexión vía Internet de dispositivos que no se concibieron tradicionalmente como activos de TI, pero que ahora incluyen conectividad de red y competencias informáticas integradas.'}
    [pscustomobject]@{term='IT asset';termino='activo de TI';english='Any financially valuable component that can contribute to the delivery of an IT product or service.';spanish='Cualquier componente con valor financiero que pueda contribuir a la entrega de un servicio o producto de TI.'}
    [pscustomobject]@{term='IT asset management practice';termino='práctica de gestión de activos de TI';english='The practice of planning and managing the full lifecycle of all IT assets.';spanish='Práctica que consiste en planificar y gestionar el ciclo de vida completo de todos los activos de TI.'}
    [pscustomobject]@{term='IT infrastructure';termino='infraestructura de TI';english='All of the hardware, software, networks, and facilities that are required to develop, test, deliver, monitor, manage, and support IT services.';spanish='Todo el hardware, el software, las redes y las instalaciones que se necesitan para desarrollar, probar, entregar, monitorear y gestionar, así como dar soporte a los servicios de TI.'}
    [pscustomobject]@{term='IT service';termino='servicio de TI';english='A service based on the use of information technology.';spanish='Servicio basado en el uso de tecnología de la información.'}
    [pscustomobject]@{term='ITIL';termino='ITIL';english='Best-practice guidance for IT service management.';spanish='Orientación sobre las mejores prácticas para la gestión de servicios de TI.'}
    [pscustomobject]@{term='ITIL guiding principles';termino='principios guía de ITIL';english='Recommendations that can guide an organization in all circumstances, regardless of changes in its goals, strategies, type of work, or management structure.';spanish='Recomendaciones que pueden servir como guía para una organización en todas las circunstancias, independientemente de los cambios en sus objetivos, estrategias, tipo de trabajo o estructura de gestión.'}
    [pscustomobject]@{term='ITIL service value chain';termino='cadena de valor del servicio de ITIL';english='An operating model for service providers that covers all the key activities required to effectively manage products and services.';spanish='Modelo de operación para los proveedores de servicios que cubre todas las actividades clave requeridas para gestionar los productos y los servicios de forma eficaz.'}
    [pscustomobject]@{term='Kanban';termino='Kanban';english='A method for visualizing work, identifying potential blockages and resource conflicts, and managing work in progress.';spanish='Método que permite visualizar el trabajo, identificar posibles bloqueos y conflictos entre recursos, y gestionar el trabajo en curso.'}
    [pscustomobject]@{term='key performance indicator (KPI)';termino='indicador clave de desempeño (KPI)';english='An important metric used to evaluate the success in meeting an objective.';spanish='Métrica importante que se usa para evaluar el éxito en la consecución de un objetivo.'}
    [pscustomobject]@{term='knowledge management practice';termino='práctica de gestión del conocimiento';english='The practice of maintaining and improving the effective, efficient, and convenient use of information and knowledge across an organization.';spanish='Práctica que consiste en mantener y mejorar el uso eficaz, eficiente y conveniente de conocimiento e información en toda la organización.'}
    [pscustomobject]@{term='known error';termino='error conocido';english='A problem that has been analysed but has not been resolved.';spanish='Un problema que se ha analizado pero no se ha resuelto.'}
    [pscustomobject]@{term='Lean';termino='Lean';english='An approach that focuses on improving workflows by maximizing value through the elimination of waste.';spanish='Enfoque que se centra en mejorar los flujos de trabajo mediante la eliminación de pérdidas y la consecuente maximización del valor.'}
    [pscustomobject]@{term='lifecycle';termino='ciclo de vida';english='The full set of stages, transitions, and associated statuses in the life of a service, product, practice, or other entity.';spanish='Conjunto completo de fases, transiciones y estados asociados en la vida de un servicio, producto, práctica u otra entidad.'}
    [pscustomobject]@{term='live';termino='en producción';english='Refers to a service or other configuration item operating in the live environment.';spanish='Se refiere a un servicio u otro elemento de configuración que funciona en el ambiente de producción.'}
    [pscustomobject]@{term='live environment';termino='ambiente de producción';english='A controlled environment used in the delivery of IT services to service consumers.';spanish='Ambiente controlado que se usa para proporcionar servicios de TI a los clientes de servicios.'}
    [pscustomobject]@{term='maintainability';termino='capacidad de dar mantenimiento';english='The ease with which a service or other entity can be repaired or modified.';spanish='Facilidad con la que un servicio u otra entidad se pueden reparar o modificar.'}
    [pscustomobject]@{term='major incident';termino='incidente mayor';english='An incident with significant business impact, requiring an immediate coordinated resolution.';spanish='Incidente con un impacto significativo en el negocio, que requiere una resolución coordinada inmediata.'}
    [pscustomobject]@{term='management system';termino='sistema de gestión';english='Interrelated or interacting elements that establish policy and objectives and enable the achievement of those objectives.';spanish='Elementos interrelacionados o que interactúan entre ellos, que establecen la política y los objetivos, y permiten conseguir dichos objetivos.'}
    [pscustomobject]@{term='maturity';termino='madurez';english='A measure of the reliability, efficiency and effectiveness of an organization, practice, or process.';spanish='Medida de la confiabilidad, eficiencia y eficacia de una organización, práctica o proceso.'}
    [pscustomobject]@{term='mean time between failures (MTBF)';termino='tiempo medio entre fallas (MTBF)';english='A metric of how frequently a service or other configuration item fails.';spanish='Métrica que indica la frecuencia con la que un servicio u otro elemento de configuración falla.'}
    [pscustomobject]@{term='mean time to restore service (MTRS)';termino='tiempo medio para restablecer el servicio (MTRS)';english='A metric of how quickly a service is restored after a failure.';spanish='Métrica que indica con qué rapidez se restaura un servicio después de una falla.'}
    [pscustomobject]@{term='measurement and reporting';termino='medición e informes';english='The practice of supporting good decision-making and continual improvement by decreasing levels of uncertainty.';spanish='Práctica que consiste en propiciar una toma de decisiones adecuada y la mejora continua mediante la disminución de los niveles de incertidumbre.'}
    [pscustomobject]@{term='metric';termino='métrica';english='A measurement or calculation that is monitored or reported for management and improvement.';spanish='Medida o cálculo que se monitorea o informa con fines de gestión y mejora.'}
    [pscustomobject]@{term='minimum viable product (MVP)';termino='producto mínimo viable (MVP)';english='A product with just enough features to satisfy early customers, and to provide feedback for future product development.';spanish='Producto con las funciones suficientes para satisfacer a los clientes iniciales y proporcionar retroalimentación para un posterior desarrollo del producto.'}
    [pscustomobject]@{term='mission statement';termino='declaración de intenciones ';english='A short but complete description of the overall purpose and intentions of an organization. It states what is to be achieved, but not how this should be done.';spanish='Descripción breve pero completa del propósito y las intenciones generales de una organización. Expone lo que se pretende lograr, pero no cómo se debe hacer.'}
    [pscustomobject]@{term='model';termino='modelo';english='A representation of a system, practice, process, service, or other entity that is used to understand and predict its behaviour and relationships.';spanish='Representación de un sistema, una práctica, un proceso, un servicio u otra entidad que se utiliza para entender y predecir su comportamiento y sus relaciones.'}
    [pscustomobject]@{term='modelling';termino='modelado';english='The activity of creating, maintaining, and utilizing models.';spanish='Actividad de crear, mantener y utilizar modelos.'}
    [pscustomobject]@{term='monitoring';termino='monitoreo';english='Repeated observation of a system, practice, process, service, or other entity to detect events and to ensure that the current status is known.';spanish='Observación repetida de un sistema, una práctica, un proceso, un servicio u otra entidad con el objetivo de conocer su estado actual y detectar posibles eventos.'}
    [pscustomobject]@{term='monitoring and event management practice';termino='práctica de monitoreo y gestión de eventos';english='The practice of systematically observing services and service components, and recording and reporting selected changes of state identified as events.';spanish='La práctica que consiste en observar de manera sistemática los servicios y componentes de estos, así como en registrar e informar de determinados cambios de estado identificados como eventos.'}
    [pscustomobject]@{term='obtain/build';termino='obtener/construir';english='The value chain activity that ensures service components are available when and where they are needed, and that they meet agreed specifications.';spanish='Actividad de la cadena de valor para asegurar que los componentes de servicio están disponibles cuándo y dónde se necesitan, y que cumplen las especificaciones acordadas.'}
    [pscustomobject]@{term='operation';termino='operación';english='The routine running and management of an activity, product, service, or other configuration item.';spanish='Rutina que ejecuta y gestiona una actividad, un producto, un servicio u otro elemento de configuración.'}
    [pscustomobject]@{term='operational technology';termino='tecnología operacional';english='The hardware and software solutions that detect or cause changes in physical processes through direct monitoring and/or control of physical devices such as valves, pumps, etc.';spanish='Soluciones de hardware y software que sirven para detectar o aplicar cambios en procesos físicos mediante el monitoreo o control directo de dispositivos físicos como válvulas, bombas, etc.'}
    [pscustomobject]@{term='organization';termino='organización';english='A person or a group of people that has its own functions with responsibilities, authorities, and relationships to achieve its objectives.';spanish='Persona o grupo de personas con funciones propias que involucran responsabilidades, autoridades y relaciones, y cuyo fin es la consecución de sus propios objetivos.'}
    [pscustomobject]@{term='organizational change management practice';termino='práctica de gestión del cambio organizacional';english='The practice of ensuring that changes in an organization are smoothly and successfully implemented and that lasting benefits are achieved by managing the human aspects of the changes.';spanish='Práctica que consiste en asegurar que los cambios que se realizan en una organización se implementan correctamente y sin contratiempos, y que los beneficios perduran gracias a la gestión del aspecto/factor humano. '}
    [pscustomobject]@{term='organizational resilience';termino='resiliencia organizacional';english='The ability of an organization to anticipate, prepare for, respond to, and adapt to unplanned external influences.';spanish='Capacidad de una organización de anticipación, preparación, respuesta y adaptación ante influencias externas no previstas.'}
    [pscustomobject]@{term='organizational velocity';termino='agilidad organizacional';english='The speed, effectiveness, and efficiency with which an organization operates. Organizational velocity influences time to market, quality, safety, costs, and risks.';spanish='Velocidad, eficacia y eficiencia con las que opera una organización. La agilidad organizacional influye en el tiempo de salida al mercado, la calidad, la seguridad, los costos y los riesgos.'}
    [pscustomobject]@{term='organizations and people';termino='organizaciones y personas';english='One of the four dimensions of service management. It ensures that the way an organization is structured and managed, as well as its roles, responsibilities, and systems of authority and communication, is well defined and supports its overall strategy and operating model.';spanish='Una de las cuatro dimensiones de la gestión de servicios. Asegura que la forma en que se estructura y gestiona una organización, así como sus roles, responsabilidades y sistemas de autoridad y comunicación, están definidos adecuadamente y respaldan su estrategia global y su modelo de operación.'}
    [pscustomobject]@{term='outcome';termino='consecuencia';english='A result for a stakeholder enabled by one or more outputs.';spanish='Resultado que obtiene una parte interesada (stakeholder), sustentado por una o más instancias de salidas obtenidas.'}
    [pscustomobject]@{term='output';termino='salida';english='A tangible or intangible deliverable of an activity.';spanish='Entregable tangible o intangible de una actividad.'}
    [pscustomobject]@{term='outsourcing';termino='externalización (tercerización)';english='The process of having external suppliers provide products and services that were previously provided internally.';spanish='Proceso mediante el cual los proveedores externos proporcionan productos y servicios que anteriormente se proporcionaban de manera interna.'}
    [pscustomobject]@{term='partners and suppliers';termino='aliados y proveedores';english='One of the four dimensions of service management. It encompasses the relationships an organization has with other organizations that are involved in the design, development, deployment, delivery, support, and/or continual improvement of services.';spanish='Una de las cuatro dimensiones de la gestión de servicios. Engloba las relaciones que mantiene una organización con otras involucradas en el diseño, el desarrollo, la implementación, la entrega, el apoyo o la mejora continua de los servicios.'}
    [pscustomobject]@{term='partnership';termino='alianza ';english='A relationship between two organizations that involves working closely together to achieve common goals and objectives.';spanish='Relación entre dos organizaciones que requiere trabajar en estrecha colaboración para alcanzar metas y objetivos comunes. '}
    [pscustomobject]@{term='performance';termino='desempeño';english='A measure of what is achieved or delivered by a system, person, team, practice, or service.';spanish='Medición de los resultados alcanzados o entregados por un sistema, una persona, un equipo, una práctica o un servicio.'}
    [pscustomobject]@{term='pilot';termino='piloto';english='A test implementation of a service with a limited scope in a live environment.';spanish='Implementación de prueba de un servicio con un alcance limitado en un ambiente de producción.'}
    [pscustomobject]@{term='plan';termino='planear';english='The value chain activity that ensures a shared understanding of the vision, current status, and improvement direction for all four dimensions and all products and services across an organization.';spanish='Actividad de la cadena de valor que asegura una comprensión compartida de la visión, el estado actual y el objetivo de mejora para las cuatro dimensiones y los productos y servicios de una organización.'}
    [pscustomobject]@{term='policy';termino='política';english='Formally documented management expectations and intentions, used to direct decisions and activities.';spanish='Gestión de expectativas e intenciones formalmente documentadas para su uso directo en la toma de decisiones y actividades.'}
    [pscustomobject]@{term='portfolio management practice';termino='práctica de gestión del portafolio';english='The practice of ensuring that an organization has the right mix of programmes, projects, products, and services to execute its strategy within its funding and resource constraints.';spanish='Práctica que consiste en garantizar que una organización dispone de la combinación adecuada de programas, proyectos, productos y servicios para ejecutar su estrategia dentro de su presupuesto y recursos.'}
    [pscustomobject]@{term='post-implementation review (PIR)';termino='revisión postimplementación (PIR)';english='A review after the implementation of a change, to evaluate success and identify opportunities for improvement.';spanish='Revisión posterior a la implementación de un cambio para evaluar su éxito e identificar oportunidades de mejora.'}
    [pscustomobject]@{term='practice';termino='práctica';english='A set of organizational resources designed for performing work or accomplishing an objective.';spanish='Conjunto de recursos organizacionales diseñados para llevar a cabo un trabajo o lograr un objetivo.'}
    [pscustomobject]@{term='problem';termino='problema';english='A cause, or potential cause, of one or more incidents.';spanish='Causa o causa potencial de uno o más incidentes.'}
    [pscustomobject]@{term='problem management practice';termino='práctica de gestión de problemas';english='The practice of reducing the likelihood and impact of incidents by identifying actual and potential causes of incidents, and managing workarounds and known errors.';spanish='Práctica que consiste en reducir la probabilidad y el impacto de incidentes mediante la identificación de sus causas reales y potenciales y la gestión de soluciones temporales y errores conocidos.'}
    [pscustomobject]@{term='procedure';termino='procedimiento';english='A documented way to carry out an activity or a process.';spanish='Forma documentada de llevar a cabo una actividad o un proceso.'}
    [pscustomobject]@{term='process';termino='proceso';english='A set of interrelated or interacting activities that transform inputs into outputs. A process takes one or more defined inputs and turns them into defined outputs. Processes define the sequence of actions and their dependencies.';spanish='Conjunto de actividades interrelacionadas o que interactúan entre sí, transformando entradas en salidas. Un proceso toma una o más entradas definidas y las transforma en salidas concretas. Los procesos determinan la secuencia de las acciones y sus dependencias.'}
    [pscustomobject]@{term='product';termino='producto';english='A configuration of an organization"s resources designed to offer value for a consumer.';spanish='Configuración de los recursos de una organización diseñada para ofrecer valor añadido a un consumidor.'}
    [pscustomobject]@{term='production environment';termino='ambiente de producción ';english='See live environment.';spanish='Véase ambiente en producción.'}
    [pscustomobject]@{term='programme';termino='programa';english='A set of related projects and activities, and an organization structure created to direct and oversee them.';spanish='Conjunto de actividades y proyectos relacionados, y la estructura de la organización creada para dirigirlos y supervisarlos.'}
    [pscustomobject]@{term='project';termino='proyecto';english='A temporary structure that is created for the purpose of delivering one or more outputs (or products) according to an agreed business case.';spanish='Estructura temporal que se crea con la finalidad de entregar una o más salidas (o productos) de conformidad con un caso de negocio acordado.'}
    [pscustomobject]@{term='project management practice';termino='práctica de gestión de proyectos';english='The practice of ensuring that all an organization"s projects are successfully delivered.';spanish='Práctica que consiste en asegurar la entrega correcta de los proyectos de una organización.'}
    [pscustomobject]@{term='quick win';termino='ganancia rápida';english='An improvement that is expected to provide a return on investment in a short period of time with relatively small cost and effort.';spanish='Mejora de la que se espera un retorno sobre la inversión en un período de tiempo breve con un costo y esfuerzo relativamente bajos.'}
    [pscustomobject]@{term='record';termino='registro';english='A document stating results achieved and providing evidence of activities performed.';spanish='Documento donde se exponen los resultados obtenidos y se proporcionan evidencias de las actividades realizadas.'}
    [pscustomobject]@{term='recovery';termino='recuperación';english='The activity of returning a configuration item to normal operation after a failure.';spanish='Actividad que consiste en regresar un elemento de configuración a su operación normal después de una falla.'}
    [pscustomobject]@{term='recovery point objective (RPO) ';termino='objetivo de punto de recuperación (RPO) ';english='The point to which information used by an activity must be restored to enable the activity to operate on resumption.';spanish='Punto al que se debe restaurar la información usada por una actividad, para que esta pueda operar tras la reanudación.'}
    [pscustomobject]@{term='recovery time objective (RTO) ';termino='objetivo de tiempo de recuperación (RTO) ';english='The maximum acceptable period of time following a service disruption that can elapse before the lack of business functionality severely impacts the organization.';spanish='Período de tiempo máximo aceptable que puede transcurrir desde la interrupción de un servicio antes de que la falta del funcionamiento del negocio repercuta gravemente en la organización.'}
    [pscustomobject]@{term='relationship management practice';termino='práctica de gestión de relaciones';english='The practice of establishing and nurturing links between an organization and its stakeholders at strategic and tactical levels.';spanish='Práctica que consiste en establecer y promover vínculos entre una organización y otras partes interesadas en niveles tácticos y estratégicos.'}
    [pscustomobject]@{term='release';termino='liberación';english='A version of a service or other configuration item, or a collection of configuration items, that is made available for use.';spanish='Versión de un servicio u otro elemento de configuración, o recopilación de elementos de configuración, que están disponibles para utilizarse.'}
    [pscustomobject]@{term='release management practice';termino='práctica de gestión de liberaciones';english='The practice of making new and changed services and features available for use.';spanish='Práctica que consiste en hacer que funciones y servicios, tanto nuevos como modificados, estén disponibles para usarse.'}
    [pscustomobject]@{term='reliability';termino='confiabilidad';english='The ability of a product, service, or other configuration item to perform its intended function for a specified period of time or number of cycles.';spanish='Capacidad de un producto, servicio u otro elemento de configuración de realizar su función prevista durante un período de tiempo o un número de ciclos especificados.'}
    [pscustomobject]@{term='request catalogue';termino='catálogo de solicitudes';english='A view of the service catalogue, providing details on service requests for existing and new services, which is made available for the user.';spanish='Vista del catálogo de servicios disponible para el usuario que proporciona información sobre las solicitudes de servicios nuevos y existentes.'}
    [pscustomobject]@{term='request for change (RFC) ';termino='solicitud de cambio (RFC) ';english='A description of a proposed change used to initiate change control.';spanish='Descripción de un cambio propuesto que sirve para iniciar el control de cambios.'}
    [pscustomobject]@{term='resolution';termino='resolución';english='The action of solving an incident or problem.';spanish='Acción de resolver un incidente o problema.'}
    [pscustomobject]@{term='resource';termino='recurso';english='A person, or other entity, that is required for the execution of an activity or the achievement of an objective. Resources used by an organization may be owned by the organization or used according to an agreement with the resource owner.';spanish='Persona u otra entidad que se requiere para la ejecución de una actividad o la consecución de un objetivo. Una organización puede usar recursos propios o, mediante un acuerdo, recursos de otro propietario.'}
    [pscustomobject]@{term='retire';termino='retiro';english='The act of permanently withdrawing a product, service, or other configuration item from use.';spanish='Acto de retirar de forma permanente el uso de un producto, servicio u otro elemento de configuración.'}
    [pscustomobject]@{term='risk';termino='riesgo';english='A possible event that could cause harm or loss, or make it more difficult to achieve objectives. Can also be defined as uncertainty of outcome, and can be used in the context of measuring the probability of positive outcomes as well as negative outcomes.';spanish='Posible evento que puede causar daños o pérdidas, o dificultar más la consecución de objetivos. El riesgo también se puede definir como incertidumbre de las consecuencias y puede usarse para medir la probabilidad de obtener resultados positivos o negativos.'}
    [pscustomobject]@{term='risk assessment';termino='evaluación de riesgos';english='An activity to identify, analyse, and evaluate risks.';spanish='Actividad que permite identificar, analizar y evaluar riesgos.'}
    [pscustomobject]@{term='risk management practice';termino='práctica de gestión de riesgos';english='The practice of ensuring that an organization understands and effectively handles risks.';spanish='Práctica que consiste en garantizar que una organización entiende y gestiona los riesgos de un modo eficaz.'}
    [pscustomobject]@{term='service';termino='servicio';english='A means of enabling value co-creation by facilitating outcomes that customers want to achieve, without the customer having to manage specific costs and risks.';spanish='Medio para posibilitar la creación conjunta de valor al facilitar las consecuencias que los clientes desean obtener sin que estos asuman costos ni riesgos específicos.'}
    [pscustomobject]@{term='service action';termino='acción de servicio';english='Any action required to deliver a service output to a user. Service actions may be performed by a service provider resource, by service users, or jointly.';spanish='Cualquier acción requerida para entregar la salida de un servicio a un usuario. Las acciones de servicio pueden realizarlas los recursos de un proveedor de servicios, los usuarios del servicio o ambos en conjunto.'}
    [pscustomobject]@{term='service architecture';termino='arquitectura de servicios';english='A view of all the services provided by an organization. It includes interactions between the services, and service models that describe the structure and dynamics of each service.';spanish='Vista de todos los servicios proporcionados por una organización, incluidas las interacciones entre los servicios, y los modelos de servicio que describen la estructura y dinámica de cada servicio.'}
    [pscustomobject]@{term='service catalogue';termino='catálogo de servicios';english='Structured information about all the services and service offerings of a service provider, relevant for a specific target audience.';spanish='Información estructurada sobre los servicios y ofertas de servicio de un proveedor, relevante para una audiencia objetivo específica.'}
    [pscustomobject]@{term='service catalogue management practice';termino='práctica de gestión del catálogo de servicios';english='The practice of providing a single source of consistent information on all services and service offerings, and ensuring that it is available to the relevant audience.';spanish='Práctica que consiste en ofrecer una sola fuente de información fidedigna en todos los servicios y ofertas de servicio, y en garantizar que dicha información esté disponible para la audiencia relevante.'}
    [pscustomobject]@{term='service configuration management practice';termino='práctica de gestión de la configuración de servicios';english='The practice of ensuring that accurate and reliable information about the configuration of services, and the configuration items that support them, is available when and where needed.';spanish='Práctica que consiste en garantizar que la información precisa y confiable sobre la configuración de servicios, y los elementos de configuración detrás de estos, esté disponible en el momento y lugar que se requiera.'}
    [pscustomobject]@{term='service consumption';termino='consumo de servicios';english='Activities performed by an organization to consume services. It includes the management of the consumer"s resources needed to use the service, service actions performed by users, and the receiving (acquiring) of goods (if required).';spanish='Actividades realizadas por una organización que derivan en el uso de servicios, incluidas la gestión de los recursos del consumidor necesarios para usar el servicio, las acciones de servicio realizadas por los usuarios y la recepción (adquisición) de bienes, si fuera necesario.'}
    [pscustomobject]@{term='service continuity management practice';termino='práctica de gestión de la continuidad del servicio';english='The practice of ensuring that service availability and performance are maintained at a sufficient level in case of a disaster.';spanish='Práctica que consiste en asegurar un nivel suficiente de disponibilidad y desempeño del servicio en caso de desastre.'}
    [pscustomobject]@{term='service design practice';termino='práctica de diseño del servicio';english='The practice of designing products and services that are fit for purpose, fit for use, and that can be delivered by the organization and its ecosystem.';spanish='Práctica que consiste en diseñar productos y servicios adecuados para su propósito y su uso, y que la organización y su ecosistema puedan entregar.'}
    [pscustomobject]@{term='service desk';termino='mesa de servicio';english='The point of communication between the service provider and all its users.';spanish='Punto de comunicación entre el proveedor de servicios y sus usuarios.'}
    [pscustomobject]@{term='service desk practice';termino='práctica de mesa de servicio';english='The practice of capturing demand for incident resolution and service requests.';spanish='Práctica que consiste en registrar peticiones para resolver incidentes y solicitudes de servicio.'}
    [pscustomobject]@{term='service financial management practice';termino='práctica de gestión financiera de servicios';english='The practice of supporting an organization"s strategies and plans for service management by ensuring that the organization"s financial resources and investments are being used effectively.';spanish='Práctica que consiste en apoyar las estrategias y los planes de una organización orientados a la gestión de servicios, al garantizar que las inversiones y los recursos financieros de la organización se usen de forma eficaz.'}
    [pscustomobject]@{term='service level';termino='nivel de servicio';english='One or more metrics that define expected or achieved service quality.';spanish='Una o más métricas que definen la calidad de servicio esperada o alcanzada.'}
    [pscustomobject]@{term='service level agreement (SLA)';termino='acuerdo de niveles de servicio (SLA)';english='A documented agreement between a service provider and a customer that identifies both services required and the expected level of service.';spanish='Acuerdo documentado entre un proveedor de servicios y un cliente, en el que se especifican tanto los servicios requeridos como el nivel de servicio esperado.'}
    [pscustomobject]@{term='service level management practice';termino='práctica de gestión de niveles de servicio';english='The practice of setting clear business-based targets for service performance so that the delivery of a service can be properly assessed, monitored, and managed against these targets.';spanish='Práctica que consiste en definir con claridad los objetivos de desempeño comercial de los servicios, de modo que se puedan usar para evaluar, monitorear y gestionar adecuadamente la entrega de un servicio.'}
    [pscustomobject]@{term='service management';termino='gestión de servicios';english='A set of specialized organizational capabilities for enabling value for customers in the form of services.';spanish='Conjunto de capacidades organizacionales especializadas orientadas a ofrecer valor a los clientes en forma de servicios.'}
    [pscustomobject]@{term='service offering';termino='oferta de servicios';english='A formal description of one or more services, designed to address the needs of a target consumer group. A service offering may include goods, access to resources, and service actions.';spanish='Descripción formal de uno o más servicios, diseñada para satisfacer las necesidades de un grupo de consumidores objetivo. Una oferta de servicios puede incluir bienes, acceso a recursos y acciones de servicio.'}
    [pscustomobject]@{term='service owner';termino='propietario del servicio';english='A role that is accountable for the delivery of a specific service.';spanish='Rol responsable de la entrega de un servicio específico.'}
    [pscustomobject]@{term='service portfolio';termino='portafolio de servicios';english='A complete set of products and services that are managed throughout their lifecycles by an organization.';spanish='Conjunto completo de productos y servicios que una organización gestiona a lo largo de su ciclo de vida. '}
    [pscustomobject]@{term='service provider';termino='proveedor de servicios';english='A role performed by an organization in a service relationship to provide services to consumers.';spanish='Rol que asume una organización en una relación de servicios para proporcionar servicios a consumidores.'}
    [pscustomobject]@{term='service provision';termino='provisión de servicios';english='Activities performed by an organization to provide services. It includes management of the provider"s resources, configured to deliver the service; ensuring access to these resources for users; fulfilment of the agreed service actions; service level management; and continual improvement. It may also include the supply of goods.';spanish='Actividades que realiza una organización para ofrecer servicios. Incluyen gestionar los recursos del proveedor configurados para proporcionar el servicio, garantizar el acceso de los usuarios a dichos recursos, cumplir las acciones de servicio acordadas, gestionar el nivel de servicio y practicar la mejora continua. También pueden incluir el suministro de bienes.'}
    [pscustomobject]@{term='service relationship';termino='relación de servicio';english='A cooperation between a service provider and service consumer. Service relationships include service provision, service consumption, and service relationship management.';spanish='Cooperación entre un proveedor de servicios y un consumidor de servicios. Las relaciones de servicio incluyen la gestión de las mismas, así como el suministro y consumo del servicio.'}
    [pscustomobject]@{term='service relationship management';termino='gestión de relaciones de servicio';english='Joint activities performed by a service provider and a service consumer to ensure continual value co-creation based on agreed and available service offerings.';spanish='Actividades que realizan un proveedor de servicios y un consumidor de manera conjunta para asegurar la creación continua de valor con base en las ofertas de servicio acordadas y disponibles.'}
    [pscustomobject]@{term='service request';termino='solicitud de servicio';english='A request from a user or a user"s authorized representative that initiates a service action which has been agreed as a normal part of service delivery.';spanish='Solicitud de un usuario o del representante autorizado de un usuario que inicia una acción de servicio acordada como parte normal de la entrega de un servicio.'}
    [pscustomobject]@{term='service request management practice';termino='práctica de gestión de solicitudes de servicio';english='The practice of supporting the agreed quality of a service by handling all pre-defined, user-initiated service requests in an effective and user-friendly manner.';spanish='Práctica que consiste en respaldar la calidad acordada de un servicio mediante el manejo sencillo y eficaz de las solicitudes de servicio predefinidas e iniciadas por el usuario.'}
    [pscustomobject]@{term='service validation and testing practice';termino='práctica de validación y pruebas del servicio';english='The practice of ensuring that new or changed products and services meet defined requirements.';spanish='Práctica que consiste en asegurar que los productos y servicios nuevos o modificados cumplen con los requerimientos definidos.'}
    [pscustomobject]@{term='service value system (SVS)';termino='sistema de valor del servicio (SVS)';english='A model representing how all the components and activities of an organization work together to facilitate value creation.';spanish='Modelo que representa de qué forma todos los componentes y actividades de una organización contribuyen a la creación de valor.'}
    [pscustomobject]@{term='software development and management practice';termino='práctica de gestión y desarrollo de software';english='The practice of ensuring that applications meet stakeholder needs in terms of functionality, reliability, maintainability, compliance, and auditability.';spanish='Práctica que consiste en garantizar que las aplicaciones satisfacen las necesidades de las partes interesadas (stakeholders) en términos de funcionalidad, confiabilidad, mantenimiento, conformidad y auditabilidad.'}
    [pscustomobject]@{term='sourcing';termino='suministrar';english='The activity of planning and obtaining resources from a particular source type, which could be internal or external, centralized or distributed, and open or proprietary.';spanish='Actividad que consiste en la planificación y obtención de recursos de un tipo de aprovisionamiento particular, que puede ser interna o externa, centralizada o distribuida, y libre o de propiedad.'}
    [pscustomobject]@{term='specification';termino='especificación';english='A documented description of the properties of a product, service, or other configuration item.';spanish='Descripción documentada de las propiedades de un producto, servicio u otro elemento de configuración.'}
    [pscustomobject]@{term='sponsor';termino='patrocinador';english='A person who authorizes budget for service consumption. Can also be used to describe an organization or individual that provides financial or other support for an initiative.';spanish='Persona que autoriza el presupuesto para el consumo de servicios. También se puede usar para describir a una organización o un individuo que proporciona apoyo financiero o de otro tipo para una iniciativa.'}
    [pscustomobject]@{term='stakeholder';termino='parte interesada';english='A person or organization that has an interest or involvement in an organization, product, service, practice, or other entity.';spanish='Persona u organización que tiene un interés o participación en una organización, un producto, un servicio, una práctica u otra entidad.'}
    [pscustomobject]@{term='standard';termino='estándar';english='A document, established by consensus and approved by a recognized body, that provides for common and repeated use, mandatory requirements, guidelines, or characteristics for its subject.';spanish='Documento establecido por consenso y aprobado por un órgano reconocido que establece, para su uso repetido y común, directrices, características o requerimientos obligatorios relacionados con su tema.'}
    [pscustomobject]@{term='standard change';termino='cambio estándar';english='A low-risk, pre-authorized change that is well understood and fully documented, and which can be implemented without needing additional authorization.';spanish='Cambio previamente autorizado y de bajo riesgo que se comprende bien y está totalmente documentado, y que se puede implementar sin necesidad de obtener una autorización adicional.'}
    [pscustomobject]@{term='status';termino='estado';english='A description of the specific states an entity can have at a given time.';spanish='Descripción de los estados específicos que puede tener una entidad en un momento determinado.'}
    [pscustomobject]@{term='strategy management practice';termino='práctica de gestión estratégica';english='The practice of formulating the goals of an organization and adopting the courses of action and allocation of resources necessary for achieving those goals.';spanish='Práctica que consiste en plantear los objetivos de una organización y adoptar los cursos de acción y la asignación de recursos necesarios para alcanzarlos.'}
    [pscustomobject]@{term='supplier';termino='proveedor';english='A stakeholder responsible for providing services that are used by an organization.';spanish='Parte interesada responsable de proporcionar los servicios que utiliza una organización.'}
    [pscustomobject]@{term='supplier management practice';termino='práctica de gestión de proveedores';english='The practice of ensuring that an organization"s suppliers and their performance levels are managed appropriately to support the provision of seamless quality products and services.';spanish='Práctica que consiste en asegurar que los proveedores de una organización y sus niveles de desempeño se gestionan adecuadamente para posibilitar el suministro de productos y servicios de calidad sin interrupciones.'}
    [pscustomobject]@{term='support team';termino='equipo de soporte ';english='A team with the responsibility to maintain normal operations, address users" requests, and resolve incidents and problems related to specified products, services, or other configuration items.';spanish='Equipo que tiene la responsabilidad de mantener las operaciones habituales, gestionar las solicitudes de los usuarios, resolver incidentes y problemas relacionados con productos, servicios u otros elementos de configuración concretos.'}
    [pscustomobject]@{term='system';termino='sistema';english='A combination of interacting elements organized and maintained to achieve one or more stated purposes.';spanish='Combinación de elementos que interactúan entre sí y que se organizan y mantienen para conseguir uno o más objetivos definidos.'}
    [pscustomobject]@{term='systems thinking';termino='pensamiento sistémico';english='A holistic approach to analysis that focuses on the way that a system"s constituent parts work, interrelate, and interact over time, and within the context of other systems.';spanish='Enfoque integral del análisis que se centra en cómo funcionan las partes constitutivas de un sistema, cómo se interrelacionan e interactúan en el tiempo y en el contexto de otros sistemas.'}
    [pscustomobject]@{term='technical debt';termino='deuda técnica';english='The total rework backlog accumulated by choosing workarounds instead of system solutions that would take longer.';spanish='Lista de tareas que se deben volver a realizar y se acumularon como resultado de elegir soluciones temporales en vez de soluciones del sistema que tomarían más tiempo.'}
    [pscustomobject]@{term='test environment';termino='ambiente de prueba';english='A controlled environment established to test products, services, and other configuration items.';spanish='Ambiente controlado establecido para probar productos, servicios y otros elementos de configuración.'}
    [pscustomobject]@{term='third party';termino='terceros';english='A stakeholder external to an organization.';spanish='Parte interesada externa a una organización.'}
    [pscustomobject]@{term='throughput';termino='rendimiento';english='A measure of the amount of work performed by a product, service, or other system over a given period of time.';spanish='Valor que permite medir la cantidad de trabajo realizada por un producto, servicio u otro sistema en un período de tiempo determinado.'}
    [pscustomobject]@{term='transaction';termino='transacción';english='A unit of work consisting of an exchange between two or more participants or systems.';spanish='Unidad de trabajo que consiste en un intercambio entre dos o más participantes o sistemas.'}
    [pscustomobject]@{term='use case';termino='caso de uso';english='A technique using realistic practical scenarios to define functional requirements and to design tests.';spanish='Técnica en la que se utilizan escenarios prácticos y realistas para definir requerimientos de funcionamiento y diseñar pruebas.'}
    [pscustomobject]@{term='user';termino='usuario';english='A person who uses services.';spanish='Persona que usa los servicios.'}
    [pscustomobject]@{term='utility';termino='utilidad';english='The functionality offered by a product or service to meet a particular need. Utility can be summarized as "what the service does" and can be used to determine whether a service is "fit for purpose". To have utility, a service must either support the performance of the consumer or remove constraints from the consumer. Many services do both.';spanish='Funcionalidad de un producto o servicio para satisfacer una necesidad particular. La utilidad se puede resumir como “lo que el servicio hace” y se puede utilizar para determinar si un servicio es “adecuado para el propósito”. Para tener utilidad, un servicio debe contribuir al desempeño del consumidor o eliminar las restricciones que tenga. Muchos servicios cumplen estas dos funciones.'}
    [pscustomobject]@{term='utility requirements';termino='requerimientos de utilidad';english='Functional requirements which have been defined by the customer and are unique to a specific product.';spanish='Requerimientos de funcionamiento que el cliente ha definido y que son exclusivos de un producto concreto.'}
    [pscustomobject]@{term='validation';termino='validación';english='Confirmation that the system, product, service, or other entity meets the agreed specification.';spanish='Confirmación de que el sistema, producto, servicio u otra entidad cumplen la especificación acordada.'}
    [pscustomobject]@{term='value';termino='valor';english='The perceived benefits, usefulness, and importance of something.';spanish='Utilidad, importancia y beneficios percibidos de algo.'}
    [pscustomobject]@{term='value stream';termino='flujo de valor';english='A series of steps an organization undertakes to create and deliver products and services to consumers.';spanish='Serie de pasos que una organización lleva a cabo para crear y ofrecer productos y servicios a los consumidores.'}
    [pscustomobject]@{term='value streams and processes';termino='procesos y flujos de valor';english='One of the four dimensions of service management. It defines the activities, workflows, controls, and procedures needed to achieve the agreed objectives.';spanish='Una de las cuatro dimensiones de la gestión de servicios. Define las actividades, los flujos de trabajo, los controles y los procedimientos necesarios para lograr los objetivos acordados.'}
    [pscustomobject]@{term='vision';termino='visión';english='A defined aspiration of what an organization would like to become in the future.';spanish='Aspiración definida de lo que la organización quiere llegar a ser en el futuro.'}
    [pscustomobject]@{term='warranty';termino='garantía';english='Assurance that a product or service will meet agreed requirements. Warranty can be summarized as "how the service performs" and can be used to determine whether a service is "fit for use". Warranty often relates to service levels aligned with the needs of service consumers. This may be based on a formal agreement, or it may be a marketing message or brand image. Warranty typically addresses such areas as the availability of the service, its capacity, levels of security, and continuity. A service may be said to provide acceptable assurance, or "warranty", if all defined and agreed conditions are met.';spanish='Certeza de que un producto o servicio cumplirá con los requerimientos acordados. La garantía se puede resumir como "la forma en que se entrega el servicio" y puede utilizarse para determinar si un servicio es "adecuado para el uso". A menudo, la garantía hace referencia a niveles de servicio que se alinean con las necesidades de los consumidores del servicio; se puede basar en un acuerdo oficial, o puede ser un mensaje de mercadotecnia o una imagen de marca. Normalmente la garantía afecta a áreas como la disponibilidad del servicio, su capacidad, los niveles de seguridad y la continuidad. Se puede afirmar que un servicio proporciona un nivel de confiabilidad, o garantía, aceptable cuando se cumplen todas las condiciones definidas y acordadas.'}
    [pscustomobject]@{term='warranty requirements';termino='requerimientos de la garantía';english='Typically non-functional requirements captured as inputs from key stakeholders and other practices.';spanish='Requerimientos que habitualmente no se relacionan con el funcionamiento y se registran como datos de entrada de partes interesadas clave y otras prácticas.'}
    [pscustomobject]@{term='waterfall method';termino='método en cascada';english='A development approach that is linear and sequential with distinct objectives for each phase of development.';spanish='Enfoque de desarrollo lineal y secuencial con diferentes objetivos para cada fase del desarrollo.'}
    [pscustomobject]@{term='work instruction';termino='instrucción de trabajo';english='A detailed description to be followed in order to perform an activity.';spanish='Descripción detallada que se debe seguir para realizar una actividad.'}
    [pscustomobject]@{term='workaround';termino='solución temporal';english='A solution that reduces or eliminates the impact of an incident or problem for which a full resolution is not yet available. Some workarounds reduce the likelihood of incidents.';spanish='Solución que reduce o elimina el impacto de un incidente o problema mientras no está disponible una solución definitiva. Algunas soluciones temporales reducen la probabilidad de que se produzcan incidentes.'}
    [pscustomobject]@{term='workforce and talent management practice';termino='práctica de gestión de la fuerza laboral y el talento';english='The practice of ensuring that an organization has the right people with the appropriate skills and knowledge and in the correct roles to support its business objectives.';spanish='Práctica que consiste en asegurar que una organización dispone de las personas adecuadas, con las habilidades y el conocimiento pertinentes, asignadas en los roles correctos para respaldar sus objetivos de negocio.'}
    )
    
    #SE SUSTITUYEN LAS VOCALES POR PATRONES REGEX PARA BUSQUEDA CON Y SIN ACENTOS
    $busqueda = $busqueda -replace "[aAáÁ]","[aAáÁ]"
    $busqueda = $busqueda -replace "[eEéÉ]","[eEéÉ]"
    $busqueda = $busqueda -replace "[iIiÍ]","[iIiÍ]"
    $busqueda = $busqueda -replace "[oóOÓ]","[oóOÓ]"
    $busqueda = $busqueda -replace "[uUúÚ]","[uUúÚ]"
        
    #SI SE USA EL PARAMETRO EN INGLÉS SE HACE UNA BÚSQUEDA POR LOS CAMPOS EN INGLÉS, SI NO EN CASTELLANO, DEVUELVE LOS RESULTADOS
    if($English){
        return $glosario | where-object {$_.term -match $busqueda -or $_.english -match $busqueda} | select-object term,english | sort-object term | format-list
    }else{
        return $glosario | where-object {$_.termino -match $busqueda -or $_.spanish -match $busqueda} | select-object termino,spanish | sort-object termino | format-list
    }
        
}
Set-Alias -name ITIL -Value Get-ITILTermDefinition